services:

  llm: &llm
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    profiles: ["linux"]
    ports:
      - 11434:11434
    networks:
      - ai-stack-net

  llm-gpu:
    <<: *llm
    profiles: ["linux-gpu"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

# webui, nagivate to http://localhost:3000/ to use
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - llm
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://llm:11434}"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ai-stack-net

networks:
  ai-stack-net:

volumes:
  ollama: {}
  open-webui: {}
